language: node_js

node_js:
  - 8.15.0

build:
  ci:
    - npm install
    - npm test

resources:
  - name: shippable-bbs-oauth_repo
    type: gitRepo
    integration: avinci_gh
    versionTemplate:
      sourceName: Shippable/shippable-bbs-oauth
      branch: master

jobs:
  - name: publish_shippable-bbs-oauth
    type: runSh
    integrations:
      - ragesh_npm
    steps:
      - IN: shippable-bbs-oauth_repo
        switch: off
      - TASK:
          script:
            - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - pushd $(shipctl get_resource_state "shippable-bbs-oauth_repo")
            - npm publish
